# Generated by Django 3.2 on 2021-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartkado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('owner', models.CharField(max_length=200)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
