# Generated by Django 3.2 on 2021-04-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartkado', '0002_cartkado_unique_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('card_key', models.CharField(default='-', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartkado',
            name='owner',
        ),
    ]
