# Generated by Django 3.2 on 2021-04-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartkado', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
