# Generated by Django 3.2 on 2021-04-09 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cartkado', '0005_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartkado',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='cartkado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
